version: '3.8'

services:
  targets-manager:
    build: .
    container_name: targets-manager
    ports:
      - "8025:8000"
    volumes:
      # Mount the benchmarks directory
      - ./app/benchmarks:/app/app/benchmarks
      # Mount Docker socket to allow container to control Docker on host
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount Docker binary (if needed)
      # - /usr/bin/docker:/usr/bin/docker
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - targets-network

networks:
  targets-network:
    driver: bridge
