services:
  assistant-ui:
    build: ./assistant-ui
    container_name: pentesting-assist-ui
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - kali_network
  
  terminal-mcp:
    build: ./terminal-mcp
    container_name: pentesting-assist-terminal
    ports:
      - "8080:8080"  # Web terminal server
      - "8000:8000"  # MCP server via supergateway
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
    networks:
      - kali_network
    
  # kali-host:
  #   build: ./kali-host
  #   container_name: pentesting-assist-kali
  #   ports:
  #     - "2222:22"      # SSH access
  #   environment:
  #     - TERM=xterm-256color
  #   tty: true
  #   stdin_open: true
  #   restart: unless-stopped
  #   cap_add:
  #   - NET_ADMIN
  #   - NET_RAW
  

#     networks:
#       - kali_network

# volumes:
#   kali_home:
#     driver: local
#   kali_root:
#     driver: local

networks:
  kali_network:
    driver: bridge