services:
  # assistant-ui:
  #   build: ./assistant-ui
  #   container_name: pentesting-assist-ui
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped
  #   networks:
  #     - kali_network
  
  terminal-mcp:
    build: ./terminal-mcp
    container_name: pentesting-assist-terminal
    ports:
      - "9020:8080"
      - "9021:5900"
      - "8000:8000"
      - "8080:8090"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NODE_ENV=production
    privileged: true
    stdin_open: true
    tty: true
    networks:
      - kali_network

  target:
    image: kalilinux/kali-rolling
    container_name: pentesting-assist-target
    ports:
      - "8081:80"
      - "8082:443"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    stdin_open: true
    tty: true
    networks:
      - kali_network  
    
networks:
  kali_network:
    driver: bridge